spring.application.name=pedidos

spring.datasource.url=jdbc:h2:mem:pedidos
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# 1. Ativa a protecao no Feign
spring.cloud.openfeign.circuitbreaker.enabled=true

# 2. Configuracoes da chave do disjuntor ('estoque')
# Avalia as ultimas 5 requisicoes
resilience4j.circuitbreaker.instances.estoque.sliding-window-size=5

# Desarma se 50 porcento ou mais falharem (ou seja, 3 erros nas ultimas 5 tentativas)
resilience4j.circuitbreaker.instances.estoque.failure-rate-threshold=50

# Tempo que ele fica desarmado (esperando o servico voltar) antes de testar de novo: 10 segundos
resilience4j.circuitbreaker.instances.estoque.wait-duration-in-open-state=10000ms


# --- CONFIGURACOES DO RABBITMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest